name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches: [main, master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni

      - name: Install dependencies
        working-directory: ./slidev
        run: nci
    
      - name: Create site directory
        run: mkdir -p site/cours
      - name: Build all courses
        working-directory: ./slidev
        run: |
            for slides in cours/*/slides.md; do
            course=$(basename "$(dirname "$slides")")

            echo "=== Building cours $course ==="

            nr build "$slides" \
                --base "/${{ github.event.repository.name }}/cours/$course/" \
                --out "${{ github.workspace }}/site/cours/$course"
            done

      - name: Setup Pages
        uses: actions/configure-pages@v6
        with:
          enablement: true

      - uses: actions/upload-pages-artifact@v5
        with:
          path: site
      

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5